Repository openshift-service-mesh/sail-operator, pull requests merged in 2024-12, with the labels that each got.

#168 Ossm MultiTenant migration instructions
  docs/ossm/README.md
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/multi-tenancy/README.md
Labels: size/L

#177 Adding replaces to make the upgrade to tp2 work
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
Labels: size/XS

#170 [doc][OSSM-8228] Added Kiali changes between OSSM 2 and 3.
  docs/ossm/ossm2-vs-ossm3.md
Labels: okay to merge, size/S, ok-to-test

#173 [OSSM-6050][doc] Quickstart that setup OSSM with OCP observability + Kiali
  docs/ossm/README.md
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/README.MD
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/installOperators.sh
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/install_ossm3_demo.sh
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Bookinfo/bookinfo-gateway.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Bookinfo/bookinfo.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Bookinfo/traffic-generator-configmap.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Bookinfo/traffic-generator.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Kiali/kialiCr.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Kiali/kialiCrb.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Kiali/kialiOssmcCr.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Monitoring/ocpUserMonitoring.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Monitoring/podMonitor.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Monitoring/serviceMonitor.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/OSSM3/istioCni.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/OSSM3/istioIngressGateway.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/OSSM3/istiocr.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/TempoOtel/istioTelemetry.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/TempoOtel/minio.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/TempoOtel/opentelemetrycollector.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/TempoOtel/tempo.yaml
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/subscriptions.yaml
Labels: size/XXL, okay to merge
