Repository openshift-service-mesh/sail-operator, pull requests merged in 2024-11, with the labels that each got.

#165 Update discoverySelectors example to use bookinfo
  docs/ossm/create-mesh/README.md
Labels: auto-merge, okay to merge, size/M

#166 OSSM-8296: Add a mTLS configuration doc
  docs/ossm/README.md
  docs/ossm/ossm2-vs-ossm3.md
  docs/ossm/security/security-mTLS-configuration.md
Labels: size/L

#130 Add istioctl consoleclidownload
  bundle/manifests/istioctl_console.openshift.io_v1_consoleclidownload.yaml
  chart/templates/olm/consoleclidownload.yaml
Labels: okay to merge, size/S, ok-to-test

#169 Use bookinfo for injection examples
  docs/ossm/injection/README.md
Labels: size/L
