Repository openshift-service-mesh/sail-operator, pull requests merged in 2024-10, with the labels that each got.

#142 Add `docs/ossm` folder
  docs/ossm/README.md
Labels: size/XS, okay to merge

#143 OSSM-8185: Add docs for Running OSSM 2 and OSSM 3 side by side
  docs/ossm/README.md
  docs/ossm/ossm-2-and-ossm-3-side-by-side/README.md
Labels: size/L, okay to merge

#138 Add docs for istio-csr
  docs/ossm/README.md
  docs/ossm/cert-manager/README.md
Labels: size/L, ok-to-test

#147 OSSM-8200: adding doc for multiple control planes + scoping a mesh
  docs/ossm/README.md
  docs/ossm/create-mesh/README.md
  docs/ossm/multi-control-planes/README.md
Labels: size/L, okay to merge

#148 Update cert-manager integration with recommended doc style
  docs/ossm/cert-manager/README.md
Labels: needs-ok-to-test, size/L

#152 OSSM-8269: OSSM documentation for sidecar injection
  docs/ossm/injection/README.md
Labels: size/L

#154 Clarify scoping terminology for discovery selectors
  docs/ossm/create-mesh/README.md
Labels: okay to merge, size/S

#145 Add OSSM 2 vs 3 differences doc
  docs/ossm/README.md
  docs/ossm/ossm2-vs-ossm3.md
Labels: auto-merge, size/L
