Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-02, with the labels that each got.

#214 [Cherry-Pick] Add istioctl consoleclidownload (#130)
  bundle/manifests/istioctl_console.openshift.io_v1_consoleclidownload.yaml
  chart/templates/olm/consoleclidownload.yaml
Labels: okay to merge, size/S

#157 Add docs for multi-cluster Kiali setup
  docs/ossm/README.md
  docs/ossm/kiali-multi-cluster/README.md
  docs/ossm/kiali-multi-cluster/kiali-multicluster-login.png
  docs/ossm/kiali-multi-cluster/kiali-multicluster-mesh.png
  docs/ossm/kiali-multi-cluster/kiali-multicluster.png
Labels: size/L, okay to merge

#212 documentation: add docs for SMCP field mappings and unsupported fields
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/smcp-fields-migration/smcp-to-istio-mappings.md
  docs/ossm/ossm2-migration/smcp-fields-migration/unsupported-fields-in-3.md
Labels: size/L, okay to merge

#203 documentation: network policy migration
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/cluster-wide/README.md
  docs/ossm/ossm2-migration/network-policies.md
Labels: size/L, okay to merge, ok-to-test

#211 OSSM-8701: List recommendations for migration
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/possible-problems-list/README.md
Labels: okay to merge, size/S

#209 Add checks for kiali and CRD versions to migration checker
  docs/ossm/ossm2-migration/migration-checker.sh
Labels: size/L, okay to merge

#229 OSSM-6874: updating doc link in CSV
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: size/XS, okay to merge

#222 [release-3.0] Add default channel
  Makefile.vendor.mk
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: size/XS, okay to merge

#234 Using stable and stable-3.0 OLM channels
  .github/workflows/release.yaml
  Makefile.vendor.mk
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: okay to merge, size/S

#235 [release-3.0] Using stable and stable-3.0 OLM channels
  .github/workflows/release.yaml
  Makefile.vendor.mk
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: size/XS, okay to merge

#238 Add supported archs to CSV
  ossm/values.yaml
Labels: size/XS, okay to merge

#250 Set fips compliant annotation to true
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: size/XS, okay to merge

#255 FIPS: Fix missing build tag warnings
  Makefile.vendor.mk
Labels: size/XS, okay to merge

#263 Add migration docs for gateway-api gateways
  docs/ossm/ossm2-migration/gateway-migration.md
Labels: okay to merge, size/S
