Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-04, with the labels that each got.

#298 Using fixed GA versions of 1.24.3 images
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: okay to merge, size/S

#306 use 1.24.4-redhat
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  pkg/istioversion/versions.ossm.yaml
  resources/v1.24.4/charts/istiod/files/gateway-injection-template.yaml
  resources/v1.24.4/charts/istiod/files/grpc-agent.yaml
  resources/v1.24.4/charts/istiod/files/injection-template.yaml
  resources/v1.24.4/charts/istiod/files/kube-gateway.yaml
  resources/v1.24.4/charts/istiod/files/waypoint.yaml
  resources/v1.24.4/charts/istiod/templates/deployment.yaml
  resources/v1.24.4/charts/ztunnel/templates/daemonset.yaml
Labels: okay to merge, size/M

#308 Update revision based docs from issue OSSM-9038
  docs/ossm/versioning-and-upgrades/README.md
Labels: okay to merge, size/S

#311 Adding spec.replaces field to CSV to allow upgrades between channels
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
  ossm/values.yaml
Labels: size/XS, okay to merge
