Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-01, with the labels that each got.

#181 Add note and link to upstream tracing docs
  docs/ossm/ossm2-migration/README.md
Labels: size/XS, okay to merge

#178 Update docs to include mention of `IstioRevisionTag`
  docs/ossm/injection/README.md
  docs/ossm/ossm2-vs-ossm3.md
Labels: okay to merge, size/M

#179 Add cert manager migration docs
  docs/ossm/ossm2-migration/cert-manager/README.md
Labels: size/L, okay to merge

#180 Add migration checker script
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/migration-checker.sh
Labels: size/L, okay to merge

#188 Add note for how to find the rev label to multi-tenant migration docs
  docs/ossm/ossm2-migration/multi-tenancy/README.md
Labels: okay to merge, size/S

#190 Update migration checklist with more detail
  docs/ossm/ossm2-migration/README.md
Labels: size/L

#172 Adding migration guide for 2.6 cluster wide
  docs/ossm/ossm2-migration/cluster-wide/README.md
Labels: size/L, okay to merge

#200 Update cert-manager examples since tp2
  docs/ossm/cert-manager/README.md
Labels: size/XS, okay to merge

#202 OSSM-6337: add cleaning of 2.6 after migration
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/cleaning-2.6/README.md
  docs/ossm/ossm2-migration/cluster-wide/README.md
  docs/ossm/ossm2-migration/multi-tenancy/README.md
Labels: okay to merge, size/M

#204 OSSM-8732: Adding a note to migration guides where to find SMCP -> Istio
  docs/ossm/ossm2-migration/cluster-wide/README.md
  docs/ossm/ossm2-migration/multi-tenancy/README.md
Labels: size/L, okay to merge

#171 Add docs for istioctl install instruction
  docs/ossm/README.md
  docs/ossm/istioctl/README.md
Labels: okay to merge, size/M

#199 [doc][OSSM-8080] Added post-migration checklist subsection
  docs/ossm/ossm2-migration/README.md
Labels: size/XS, needs-ok-to-test, okay to merge, ok-to-test

#210 [doc] Update quickstart to use tempo directly in kiali instead of jaeger in tempo
  docs/ossm/quickstarts/ossm3-kiali-tempo-bookinfo/resources/Kiali/kialiCr.yaml
Labels: size/XS, okay to merge
