Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-06, with the labels that each got.

#343 Bump operator version to 3.0.3
  Makefile.vendor.mk
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/values.yaml
  ossm/values.yaml
Labels: okay to merge, size/S

#346 fix spelling errors
  docs/ossm/kiali/README.md
  docs/ossm/ossmc-plugin/README.md
Labels: size/XS, okay to merge

#349 Use 1.24.6-redhat helm charts
  pkg/istioversion/versions.ossm.yaml
  resources/v1.24.6/charts/istiod/files/gateway-injection-template.yaml
  resources/v1.24.6/charts/istiod/files/grpc-agent.yaml
  resources/v1.24.6/charts/istiod/files/injection-template.yaml
  resources/v1.24.6/charts/istiod/files/kube-gateway.yaml
  resources/v1.24.6/charts/istiod/files/waypoint.yaml
  resources/v1.24.6/charts/istiod/templates/deployment.yaml
  resources/v1.24.6/charts/ztunnel/templates/daemonset.yaml
Labels: okay to merge, size/S

#350 Hardcode GA version of 1.24.5 images + add 1.24.6 images placeholders
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: auto-merge, okay to merge, size/M

#366 Bump Operator Version to 3.0.4 + updated 3.0.3 GA images
  Makefile.vendor.mk
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/values.yaml
  ossm/values.yaml
Labels: okay to merge, size/M
