Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-09, with the labels that each got.

#485 Removing workaround for OCPBUGS-56758
  tests/e2e/cert-manager/cert_manager_test.go
Labels: okay to merge, size/M

#486 Prepare placeholders for OSSM 3.0.5
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: okay to merge, size/S

#487 Prepare placeholders for OSSM 3.0.5 & 3.1.2
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: okay to merge, size/M

#505 [release-3.1] Update istio module
  go.mod
  go.sum
Labels: size/XS, okay to merge

#516 [release-3.1] Bump version and update GA images
  Makefile.vendor.mk
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/values.yaml
  ossm/values.yaml
Labels: okay to merge, size/M

#517 [release-3.2] Update 3.0.5 and 3.1.1 GA images
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: okay to merge, size/M
