Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-08, with the labels that each got.

#393 Fix vendor-defaults for new versions
  pkg/istiovalues/vendor_defaults.yaml
Labels: okay to merge, size/S

#437 Update e2e-tests.yml
  .github/workflows/e2e-tests.yml
Labels: size/XS, okay to merge

#461 Adding create bucket to mapt workflow
  .github/workflows/e2e-tests.yml
Labels: okay to merge, size/S

#465 Increase mem limit of sail operator (#433)
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: okay to merge, size/S

#468 Revert "Adding support for configuring the max concurrent reconciles (#1139)
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller_test.go
  controllers/webhook/webhook_controller.go
  controllers/webhook/webhook_controller_test.go
  pkg/config/config.go
  tests/integration/api/suite_test.go
Labels: size/M

#476 Adding exec permissions to the merge_upstream script
  ossm/merge_upstream.sh
Labels: size/XS, okay to merge
