Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-03, with the labels that each got.

#273 Fixing the checker for disconnected OCP envs without redhat-operators
  docs/ossm/ossm2-migration/migration-checker.sh
Labels: okay to merge, size/M

#281 OSSM-8799: istio-must-gather version to 3.0.1
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: size/XS, okay to merge

#276 [Docs] Fix broken link in discoverySelector page
  docs/ossm/create-mesh/README.md
Labels: size/XS, okay to merge

#284 Change the OpenShift doc links to docs.redhat.com
  docs/ossm/injection/README.md
  docs/ossm/ossm-2-and-ossm-3-side-by-side/README.md
  docs/ossm/ossm2-migration/README.md
  docs/ossm/ossm2-migration/smcp-fields-migration/smcp-to-istio-mappings.md
  docs/ossm/ossm2-vs-ossm3.md
Labels: okay to merge, size/S

#289 Adding OSSM specific documentation: Versioning and upgrades
  docs/ossm/versioning-and-upgrades/README.md
Labels: size/L

#294 Revise in-place vs revision-based comparison
  docs/ossm/versioning-and-upgrades/README.md
Labels: size/XS
