Repository openshift-service-mesh/sail-operator, pull requests merged in 2025-07, with the labels that each got.

#376 [release-3.1] Do not specify replaces in the CSV
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  ossm/values.yaml
Labels: size/XS, okay to merge

#363 e2e Test for Integration OSSM and Cert Manager in Sail Operator
  tests/e2e/ambient/ambient_test.go
  tests/e2e/cert-manager/cert_manager_suite_test.go
  tests/e2e/cert-manager/cert_manager_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/XL

#382 Replace downstream images with environment variables
  Makefile.vendor.mk
  bundle/manifests/servicemeshoperator3.clusterserviceversion.yaml
  chart/values.yaml
  ossm/values.yaml
Labels: okay to merge, size/M, ok-to-test

#357 Add Ambient Waypoint docs
  docs/ossm/ambient/README.md
  docs/ossm/ambient/waypoint.md
Labels: size/L, okay to merge

#422 Sync upstream 1.26
  api/v1/values_types.gen.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  controllers/istiorevision/istiorevision_controller.go
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
  pkg/revision/dependency.go
  pkg/revision/dependency_test.go
  tests/integration/api/cni_dependency_test.go
  tests/integration/api/istio_test.go
  tests/integration/api/suite_test.go
Labels: size/XXL, tide/merge-method-merge, okay to merge
